### ISSUE TITLE
Neglected treebank, doesn't pass validation

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/UD_Faroese-OFT#10]
NEGLECTED; 2018-11-15 (TOTAL 67; 
- L3 Syntax leaf-aux-cop 16; 
- L3 Syntax  leaf-cc 1; 
- L3 Syntax leaf-mark-case 13; 
- L3 Syntax leaf-punct 2; 
- L3  Syntax rel-upos-advmod 20; 
- L3 Syntax rel-upos-nummod 2; 
- L3 Syntax  too-many-subjects 1;
- L5 Syntax cop-lemma 12

**Comment by dan-zeman** [comment]
12 errors remain after merging #11:

<pre>
Thu Nov 10 22:28:12 CET 2022
tools/check_files.pl UD_Faroese-OFT
*** PASSED ***
./validate.sh --lang fo --max-err 0 UD_Faroese-OFT/fo_oft-ud-test.conllu
[Line 440 Sent wikipedia.vislcg.txt:31:685 Node 3]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 1101 Sent wikipedia.vislcg.txt:82:1701 Node 3]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 2933 Sent wikipedia.vislcg.txt:226:4497 Node 5]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 3030 Sent wikipedia.vislcg.txt:234:4643 Node 5]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 3057 Sent wikipedia.vislcg.txt:235:4693 Node 4]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 6154 Sent wikipedia.vislcg.txt:469:9481 Node 5]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 7551 Sent wikipedia.vislcg.txt:575:11641 Node 4]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 7752 Sent wikipedia.vislcg.txt:590:11937 Node 12]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 8142 Sent wikipedia.vislcg.txt:620:12553 Node 4]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 9089 Sent wikipedia.vislcg.txt:688:14043 Node 2]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 11154 Sent wikipedia.vislcg.txt:845:17227 Node 4]: [L5 Syntax cop-lemma] 'verða' is not a copula in language [fo]
[Line 15923 Sent wikipedia.vislcg.txt:1200:24637 Node 3]: [L5 Syntax cop-lemma] 'vara' is not a copula in language [fo]
Syntax errors: 12
*** FAILED *** with 12 errors
</pre>

One of them is the copula _vara_, which should be probably spelled _vera_ (see https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_auxiliary.pl?lcode=fo).

The rest is _verða_, which seems to be allowed as a passive auxiliary but not as a copula. (And if it is correct to judge it by its German cognate _werden_ "to become", then I'd agree with it.)

**Comment by dan-zeman** [comment]
Fixed in 6644e99bb96380ef42a99048e2d92f2a41bbac39.
