### ISSUE TITLE
Føroyar -> Faroe Islands

### ISSUE THREAD

**Issue by Bjartensen** [UniversalDependencies/UD_Faroese-OFT#2]
Hey @ftyers I think `Føroyar` should be translated to `Faroe Islands` instead of `Faroe Isles`. Is that ok with you? `Faroe Isles` is not unheard of, but I very rarely see it used.

Also I wanted to ask, to make changes to the repository, should I just make changes and a commit to the `dev` branch and create a pull request? Or do you have another workflow in mind (forks/branches/etc)?

**Comment by martinpopel** [comment]
The master branch is UD treebanks is locked (pushed to only by @dan-zeman when building a new UD release). If you have write access to this repo you can push to the dev branch, but if you want to make it as a pull request, you should create a new branch and then pull-request a merge to the dev branch (not to the master).
Of course, @ftyers should have the last word.

**Comment by ftyers** [comment]
@Bjartensen "Faroe Islands" is fine for me... I think "Faroe Isles" is a bit archaic maybe?

So, feel free to change it, probably the best thing to do is to fork and make a pull request to the dev branch as @martinpopel suggests. Although, it might be better if you made the changes to the translations directly via PRing to the source in Apertium, which is [here](https://github.com/apertium/apertium-fao/blob/master/texts/wikipedia.vislcg.txt).

**Comment by Bjartensen** [comment]
Sorry @ftyers I'm not very experienced with Github.

I have cloned the apertium/apertium-fao repository, made a `dev` branch and added some changes and committed them. I tried to push the commits using `git push origin dev` but I get an error 403. I'm assuming I don't have access or something.

What do?

**Comment by ftyers** [comment]
@Bjartensen that makes two of us :D .... I think you need to send a "pull request" via the github interface, here is my suggestion:

1. Go here: https://github.com/apertium/apertium-fao
2. Top right, click on "Fork" it will ask you where you want to fork it to, you should choose Bjartensen.
3. Go to https://github.com/Bjartensen/apertium-fao and clone the repository.
4. Make your changes, commit and push them.
5. Now in https://github.com/Bjartensen/apertium-fao you should see something about "make pull request", click on it.
6. Click on the green buttons until the end, and hopefully I will receive an email saying you've submitted a PR.

It's a bit complicated, and I'm not an expert, but I think that should do.
